version: '3.7'

services:
  zipcall:
    image: tajmahal/zipcall
    ports:
      - '3000:3000'
    environment:
      - TWILIO_ACCOUNT_SID=YourAccountSIDHere
      - LOCAL_AUTH_TOKEN=YourAuthTokenHere